title: Docs
optionalCategoryIndex: true
supportedLanguages: []
properties:
  - name: Тип документа
    type: Enum
    values:
      - Пользовательская документация
      - Техническое задание
      - Черновик
  - name: Компонент
    type: Many
    values:
      - signor
      - haos
      - SPR
      - Camunda
    icon: album
    style: green
