@startuml
!theme plain

title Обработка файла и формирование заявлений

start

:Чтение входного файла;

:Инициализация логирования;

:Итерация по записям файла;

fork
    :Извлечение IIN и Mobile Phone;
    :Формирование URL запроса к API;
    :Отправка GET запроса к API;

    if (Сертификат активен и дата выпуска < 05.03.2025) then (Да)
        :Извлечение данных сертификата (FIO, IIN, Дата выпуска);
        :Формирование "Заявления";
        :Логирование успешного формирования заявления;
    else (Нет)
        :Логирование причины отказа;
    endif

    if (Ошибка) then (Да)
       :Логирование ошибки и IIN/Mobile Phone;
    else (Нет)
        :Итерация по записям файла;
    endif

end fork

:Завершение обработки;

stop
@enduml